# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atmogwada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiceatmo',
            name='config_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='indiceatmo',
            name='date_today',
            field=models.CharField(max_length=10),
        ),
    ]
