# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atmogwada', '0002_auto_20160716_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cchim', models.CharField(max_length=35)),
                ('unit', models.CharField(max_length=25)),
                ('cmet', models.CharField(max_length=5)),
                ('last_value', models.DateTimeField()),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField(null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('alt', models.PositiveSmallIntegerField()),
                ('last_update', models.DateTimeField(null=True)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='indiceatmo',
            options={'ordering': ['-record_date'], 'verbose_name': 'indice ATMO', 'verbose_name_plural': 'indices ATMO'},
        ),
        migrations.AddField(
            model_name='params',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atmogwada.Station'),
        ),
    ]
